import type { NostrEvent, NostrFilter, RelayUrl } from "@innis/nostr-core"
import { getDTag, soleTagValue } from "@innis/nostr-core"

/** NIP-29 group metadata event kind — addressable (39000), generated by the relay that hosts the group. */
export const KIND_GROUP_METADATA = 39000

/** NIP-29 group chat message kind (9) — the live chat, posted to a group via its `h` tag. */
export const KIND_GROUP_CHAT = 9

/**
 * A NIP-29 relay-based group, derived from a kind 39000 metadata event. A group is owned by the relay that hosts it, so
 * `relay` records where the metadata was read from; with `id` it addresses the group as `relay'id`. Admins, members,
 * roles and the lifecycle kinds are out of scope (ADR-0001).
 */
export interface Group {
  readonly id: string
  readonly relay: RelayUrl
  readonly name: string
  readonly about: string | null
  readonly picture: string | null
  readonly isPublic: boolean
  readonly isOpen: boolean
  readonly isRestricted: boolean
  readonly isHidden: boolean
  readonly isLiveAvSpace: boolean
}

const hasMarker = (event: NostrEvent, marker: string): boolean => event.tags.some((tag) => tag[0] === marker)

/** Filter for NIP-29 group metadata — every group on a relay, or a single group when `groupId` is given. */
export const groupMetadataFilter = (groupId?: string): NostrFilter =>
  groupId ? { kinds: [KIND_GROUP_METADATA], "#d": [groupId] } : { kinds: [KIND_GROUP_METADATA] }

/** Filter matching every chat message (kind 9) posted to a group, identified by its `h` tag. */
export const groupChatFilter = (groupId: string): NostrFilter => ({ kinds: [KIND_GROUP_CHAT], "#h": [groupId] })

const trimmedTagValue = (event: NostrEvent, name: string): string => soleTagValue(event.tags, name).value?.trim() ?? ""

/**
 * Derive a {@link Group} from a kind 39000 event read from `relay`, or `null` for another kind or a `d` tag (the group
 * id NIP-29 requires) that is absent, empty or disagreeing. A `name`, `about` or `picture` repeated with different
 * values is read as absent; values are trimmed, and an empty one falls back to the id (`name`) or `null`. Each flag
 * follows its NIP-29 marker tag: `isPublic` unless `private`, `isOpen` unless `closed`, and `isRestricted`, `isHidden`
 * and `isLiveAvSpace` when `restricted`, `hidden` and `livekit` are present.
 */
export const parseGroupMetadata = (event: NostrEvent, relay: RelayUrl): Group | null => {
  if (event.kind !== KIND_GROUP_METADATA) return null
  const id = getDTag(event.tags)
  if (id === null || id === "") return null
  return {
    id,
    relay,
    name: trimmedTagValue(event, "name") || id,
    about: trimmedTagValue(event, "about") || null,
    picture: trimmedTagValue(event, "picture") || null,
    isPublic: !hasMarker(event, "private"),
    isOpen: !hasMarker(event, "closed"),
    isRestricted: hasMarker(event, "restricted"),
    isHidden: hasMarker(event, "hidden"),
    isLiveAvSpace: hasMarker(event, "livekit"),
  }
}
