import type { NostrEvent, NostrFilter, RelayUrl } from "@innis/nostr-core"
import { getTagValue } from "@innis/nostr-core"

/** NIP-29 group metadata event kind — addressable (39000), generated by the relay that hosts the group. */
export const KIND_GROUP_METADATA = 39000

/** NIP-29 group chat message kind (9) — the live chat, posted to a group via its `h` tag. */
export const KIND_GROUP_CHAT = 9

/**
 * A NIP-29 relay-based group, derived from a kind 39000 metadata event.
 *
 * Each group is owned by the relay that hosts it, so `relay` records where this metadata was read
 * from — together with `id` it addresses the group as `relay'id`.
 *
 * Scope is consumer-first: the fields cover the metadata markers a member-facing client reads
 * (visibility, join policy, write policy, discoverability, live AV). Admins, members, roles and the
 * group-lifecycle/moderation kinds are not modelled here — nothing built against this library performs
 * those operations yet, so their shapes have not been worked out; they will be added when a consumer
 * needs them.
 */
export interface Group {
  readonly id: string
  readonly relay: RelayUrl
  readonly name: string
  readonly about: string | null
  readonly picture: string | null
  readonly isPublic: boolean
  readonly isOpen: boolean
  readonly isRestricted: boolean
  readonly isHidden: boolean
  readonly isLiveAvSpace: boolean
}

const hasMarker = (event: NostrEvent, marker: string): boolean => event.tags.some((tag) => tag[0] === marker)

/** Filter for NIP-29 group metadata — every group on a relay, or a single group when `groupId` is given. */
export const groupMetadataFilter = (groupId?: string): NostrFilter =>
  groupId ? { kinds: [KIND_GROUP_METADATA], "#d": [groupId] } : { kinds: [KIND_GROUP_METADATA] }

/** Filter matching every chat message (kind 9) posted to a group, identified by its `h` tag. */
export const groupChatFilter = (groupId: string): NostrFilter => ({ kinds: [KIND_GROUP_CHAT], "#h": [groupId] })

/**
 * Derive a {@link Group} from a kind 39000 event read from `relay`.
 *
 * Returns `null` for events of the wrong kind or with no `d` tag (the group id, which NIP-29
 * requires). Read access and join policy default to public/open unless the relay tags the group
 * `private` (only members can read) / `closed` (join requests ignored); `isRestricted` (only members
 * can write) and `isHidden` (relays hide metadata from non-members) default `false` unless their tags
 * are present. `isLiveAvSpace` reflects the spec `livekit` tag, marking a group that supports live
 * audio/video chat via a LiveKit server (NIP-29 "Live AV spaces"). Text fields are trimmed; empty
 * `name`/`about`/`picture` values collapse to the id fallback / `null`.
 */
export const parseGroupMetadata = (event: NostrEvent, relay: RelayUrl): Group | null => {
  if (event.kind !== KIND_GROUP_METADATA) return null
  const id = getTagValue(event.tags, "d")
  if (!id) return null
  return {
    id,
    relay,
    name: (getTagValue(event.tags, "name") ?? id).trim() || id,
    about: getTagValue(event.tags, "about")?.trim() || null,
    picture: getTagValue(event.tags, "picture")?.trim() || null,
    isPublic: hasMarker(event, "public") || !hasMarker(event, "private"),
    isOpen: hasMarker(event, "open") || !hasMarker(event, "closed"),
    isRestricted: hasMarker(event, "restricted"),
    isHidden: hasMarker(event, "hidden"),
    isLiveAvSpace: hasMarker(event, "livekit"),
  }
}
